version: "3.9"  # optional since v1.27.0
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  ui:
    build: ./ui
    ports:
      - "5000:80"
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
